import type { Trip } from './types'

export const routeIdentities = [
  'Weekend Escape',
  'First Trek',
  'Hardcore Trek',
  'Himachal Road Trip',
  'Group Energy',
  'Solitude + Silence',
  'High Effort / High Reward',
] as const

export const staticTrips: Trip[] = [
  {
    id: 'trip-kudremukh-monsoon',
    slug: 'kudremukh-monsoon-trek',
    title: 'Kudremukh Monsoon Trek',
    descriptor: 'Misty climbs. Mud trails. Zero performance.',
    realityNote: 'Leech country, wet shoes, and one green ridge that stays with you.',
    region: 'Karnataka',
    destination: 'Kudremukh',
    type: 'Trek',
    identityTags: ['Weekend Escape', 'First Trek', 'Group Energy'],
    durationDays: 2,
    durationLabel: '2D / 1N',
    difficulty: 'Moderate',
    season: ['Monsoon', 'Post Monsoon'],
    startingPoint: 'Bangalore',
    startingPrice: 4299,
    nextDeparture: '2026-05-09',
    spotsLeft: 6,
    groupSize: '18 max',
    altitude: '6,207 ft',
    image: '/images/forest-trail.jpg',
    gallery: ['/images/forest-trail.jpg', '/images/rocky-ascent.jpg'],
    featured: true,
    featuredRank: 1,
    highlights: ['Forest ascent', 'Rolling grasslands', 'Homestay night'],
    status: 'published',
  },
  {
    id: 'trip-harishchandragad',
    slug: 'harishchandragad-kokan-kada',
    title: 'Harishchandragad Kokan Kada',
    descriptor: 'Rock, monsoon, sweat, and the kind of silence you earn.',
    realityNote: 'A serious climb with old stone, sharp wind, and no brochure softness.',
    region: 'Maharashtra',
    destination: 'Harishchandragad',
    type: 'Trek',
    identityTags: ['Hardcore Trek', 'High Effort / High Reward', 'Solitude + Silence'],
    durationDays: 3,
    durationLabel: '3D / 2N',
    difficulty: 'Hard',
    season: ['Monsoon', 'Winter'],
    startingPoint: 'Pune',
    startingPrice: 6499,
    nextDeparture: '2026-05-22',
    spotsLeft: 4,
    groupSize: '14 max',
    altitude: '4,671 ft',
    image: '/images/rocky-ascent.jpg',
    gallery: ['/images/rocky-ascent.jpg', '/images/mountain-vista.jpg'],
    featured: true,
    featuredRank: 2,
    highlights: ['Kokan Kada edge', 'Ancient caves', 'Night trail'],
    status: 'published',
  },
  {
    id: 'trip-spiti-road',
    slug: 'spiti-road-journey',
    title: 'Spiti Road Journey',
    descriptor: 'Long roads. Thin air. Better conversations.',
    realityNote: 'Cold starts, rough roads, altitude checks, and no space for pretending.',
    region: 'Himachal',
    destination: 'Spiti',
    type: 'Road Trip',
    identityTags: ['Himachal Road Trip', 'Group Energy', 'High Effort / High Reward'],
    durationDays: 8,
    durationLabel: '8D / 7N',
    difficulty: 'Hard',
    season: ['Summer', 'Autumn'],
    startingPoint: 'Manali',
    startingPrice: 28999,
    nextDeparture: '2026-06-14',
    spotsLeft: 5,
    groupSize: '12 max',
    altitude: '14,931 ft',
    availableAddOns: [
      {
        id: 'manali-pickup',
        label: 'Manali arrival transfer',
        description: 'Shared transfer from the bus stand or hotel cluster straight to the briefing point.',
        price: 1499,
      },
      {
        id: 'cold-gear-rental',
        label: 'Cold-weather gear support',
        description: 'Extra layers and route-matched sleeping support for travellers coming in light.',
        price: 1899,
      },
      {
        id: 'route-insurance',
        label: 'Travel insurance assist',
        description: 'Basic support for weather delay and trip interruption coverage coordination.',
        price: 699,
      },
    ],
    paymentConfig: {
      displayName: 'Trek and Stay Experiences',
      upiId: 'trekandstay@upi',
      supportPhone: '919876543210',
      supportLabel: '+91 98765 43210',
      verificationEta: 'within 15 minutes during 8 AM to 10 PM',
    },
    image: '/images/mountain-vista.jpg',
    gallery: ['/images/mountain-vista.jpg', '/images/peak-summit.jpg'],
    featured: true,
    featuredRank: 3,
    highlights: ['Key Monastery', 'Chandratal road', 'High-altitude villages'],
    tripDetail: {
      heroLine: 'Eight days through thin air, long roads, and villages that do not perform for you.',
      altitudeLine: 'Spiti / 13,000 ft',
      emotionalHook:
        'This is not a vacation. This is altitude, effort, and long roads that change you slowly, then all at once.',
      realityChecks: [
        'Cold mornings before the body is ready.',
        'Long road hours with no shortcut around fatigue.',
        'Simple stays, shared spaces, and no luxury theatre.',
        'Altitude checks, weather calls, and plans that may change.',
        'Physical effort required even on the quiet days.',
      ],
      itinerary: [
        {
          day: 1,
          route: 'Manali arrival / group briefing',
          highlight: 'The road gets real before the road begins.',
          details:
            'Meet the captain, check layers and essentials, understand altitude rules, and keep the evening slow before the ascent starts.',
        },
        {
          day: 2,
          route: 'Manali to Kaza',
          highlight: 'Rough roads, thin air, first silence.',
          details:
            'A long transfer through high passes and broken terrain. The day is less about sightseeing and more about entering Spiti correctly.',
        },
        {
          day: 3,
          route: 'Kaza / Key Monastery / Kibber',
          highlight: 'Monastery morning above the valley.',
          details:
            'Move through high-altitude villages, keep pace gentle, and let the landscape reset your sense of distance.',
        },
        {
          day: 4,
          route: 'Hikkim / Komic / Langza',
          highlight: 'Postcards from places that do not perform.',
          details:
            'Visit some of the highest inhabited villages in the region with enough room to pause instead of rushing every stop.',
        },
        {
          day: 5,
          route: 'Kaza to Chandratal approach',
          highlight: 'The road becomes narrower, colder, better.',
          details:
            'A demanding road day toward the lake zone, dependent on weather and access. The captain makes the final call on movement.',
        },
        {
          day: 6,
          route: 'Chandratal / high camp night',
          highlight: 'Blue hour without signal.',
          details:
            'A slower day around the lake and camp region. Expect cold, shared warmth, and the kind of quiet no city can imitate.',
        },
        {
          day: 7,
          route: 'Chandratal to Manali',
          highlight: 'The return feels different from the arrival.',
          details:
            'Exit through the same terrain with a changed rhythm. Long road hours, fatigue, and the first feeling of completion.',
        },
        {
          day: 8,
          route: 'Manali departure',
          highlight: 'One last breakfast before everyone becomes real life again.',
          details:
            'Depart after morning checkout. Keep buffer time for onward travel because mountain roads do not care about tight flights.',
        },
      ],
      included: [
        'Trip captain and on-road coordination',
        'Stay during the route on shared basis',
        'Local transfers as per route plan',
        'Basic first-aid and altitude-aware planning',
        'Meals mentioned in the final departure brief',
      ],
      notIncluded: [
        'Flights or travel to the start point',
        'Personal gear, layers, medicines, and snacks',
        'Any activity outside the confirmed route plan',
        'Costs caused by weather delays or road closures',
        'Luxury upgrades, private rooms, or hotel-style service',
      ],
      proof: [
        {
          quote: 'No signal. Best conversations.',
          meta: 'Kaza night, last summer',
          image: '/images/campfire-night.jpg',
        },
        {
          quote: 'The road did not feel beautiful at first. Then it stayed with me.',
          meta: 'Chandratal approach',
          image: '/images/mountain-vista.jpg',
        },
        {
          quote: 'I stopped checking the time after day three.',
          meta: 'Komic village morning',
          image: '/images/peak-summit.jpg',
        },
        {
          quote: 'Harder than expected. Better because of that.',
          meta: 'Return road to Manali',
          image: '/images/rocky-ascent.jpg',
        },
        {
          quote: 'We came as strangers. The weather fixed that.',
          meta: 'Blue hour camp',
          image: '/images/forest-trail.jpg',
        },
      ],
      captains: [
        {
          name: 'Aarav Thapa',
          role: 'Route captain',
          line: 'Knows when to keep moving and when the mountain has already answered.',
          image: '/placeholder-user.jpg',
        },
        {
          name: 'Meera Bhandari',
          role: 'Ground lead',
          line: 'Handles the unglamorous parts that make the trip feel calm.',
          image: '/placeholder-user.jpg',
        },
        {
          name: 'Kabir Sen',
          role: 'Experience host',
          line: 'Keeps the group honest, warm, and never louder than the place.',
          image: '/placeholder-user.jpg',
        },
      ],
      bestSeason: 'June to October',
      finalLine: 'If the discomfort makes the route clearer instead of less attractive, this is probably your road.',
    },
    status: 'published',
  },
  {
    id: 'trip-kalsubai-night',
    slug: 'kalsubai-night-climb',
    title: 'Kalsubai Night Climb',
    descriptor: 'This one starts before sunrise for a reason.',
    realityNote: 'Metal ladders, moving headlamps, and a summit that wakes before the city.',
    region: 'Maharashtra',
    destination: 'Kalsubai',
    type: 'Weekend Escape',
    identityTags: ['Weekend Escape', 'First Trek', 'Group Energy'],
    durationDays: 2,
    durationLabel: '2D / 1N',
    difficulty: 'Beginner',
    season: ['Winter', 'Summer'],
    startingPoint: 'Mumbai',
    startingPrice: 2499,
    nextDeparture: '2026-05-02',
    spotsLeft: 9,
    groupSize: '22 max',
    altitude: '5,400 ft',
    image: '/images/peak-summit.jpg',
    featured: false,
    highlights: ['Night ascent', 'Highest point in Maharashtra', 'Sunrise summit'],
    status: 'published',
  },
  {
    id: 'trip-gokarna-coast',
    slug: 'gokarna-coastal-trail',
    title: 'Gokarna Coastal Trail',
    descriptor: 'Salt air, laterite paths, and the pause you did not know you needed.',
    realityNote: 'Beach is the setting, but the walk still asks for intent.',
    region: 'Karnataka',
    destination: 'Gokarna',
    type: 'Weekend Escape',
    identityTags: ['Weekend Escape', 'First Trek', 'Solitude + Silence'],
    durationDays: 2,
    durationLabel: '2D / 1N',
    difficulty: 'Beginner',
    season: ['Winter', 'Summer'],
    startingPoint: 'Bangalore',
    startingPrice: 4999,
    nextDeparture: '2026-05-16',
    spotsLeft: 11,
    groupSize: '16 max',
    image: '/images/campfire-night.jpg',
    featured: false,
    highlights: ['Coastal trail', 'Cliff viewpoints', 'Campfire night'],
    status: 'published',
  },
  {
    id: 'trip-hampta-pass',
    slug: 'hampta-pass-crossing',
    title: 'Hampta Pass Crossing',
    descriptor: 'Less comfort. More memory.',
    realityNote: 'River crossings, weather windows, and a pass that does not care about plans.',
    region: 'Himachal',
    destination: 'Hampta',
    type: 'Trek',
    identityTags: ['Hardcore Trek', 'Solitude + Silence', 'High Effort / High Reward'],
    durationDays: 5,
    durationLabel: '5D / 4N',
    difficulty: 'Extreme',
    season: ['Summer', 'Autumn'],
    startingPoint: 'Manali',
    startingPrice: 16499,
    nextDeparture: '2026-06-28',
    spotsLeft: 3,
    groupSize: '10 max',
    altitude: '14,100 ft',
    image: '/images/mountain-vista.jpg',
    featured: true,
    featuredRank: 4,
    highlights: ['Pass crossing', 'Camp nights', 'Lahaul descent'],
    status: 'published',
  },
  {
    id: 'trip-tadiandamol',
    slug: 'tadiandamol-coorg-trek',
    title: 'Tadiandamol Coorg Trek',
    descriptor: 'For first-timers with real intent.',
    realityNote: 'Coffee country below, cloudline above, and a climb that stays honest.',
    region: 'Karnataka',
    destination: 'Coorg',
    type: 'Trek',
    identityTags: ['First Trek', 'Weekend Escape', 'Group Energy'],
    durationDays: 2,
    durationLabel: '2D / 1N',
    difficulty: 'Moderate',
    season: ['Winter', 'Post Monsoon'],
    startingPoint: 'Bangalore',
    startingPrice: 3799,
    nextDeparture: '2026-05-30',
    spotsLeft: 8,
    groupSize: '18 max',
    altitude: '5,735 ft',
    image: '/images/forest-trail.jpg',
    featured: false,
    highlights: ['Coorg trails', 'Ridge walk', 'Estate stay'],
    status: 'published',
  },
  {
    id: 'trip-bir-billing-road',
    slug: 'bir-billing-road-week',
    title: 'Bir Billing Road Week',
    descriptor: 'Small group. Big route. No hurry.',
    realityNote: 'Roadside dhabas, mountain weather, and slow evenings that do the work.',
    region: 'Himachal',
    destination: 'Bir Billing',
    type: 'Road Trip',
    identityTags: ['Himachal Road Trip', 'Solitude + Silence', 'Group Energy'],
    durationDays: 6,
    durationLabel: '6D / 5N',
    difficulty: 'Moderate',
    season: ['Spring', 'Autumn'],
    startingPoint: 'Delhi',
    startingPrice: 21999,
    nextDeparture: '2026-06-05',
    spotsLeft: 7,
    groupSize: '12 max',
    image: '/images/campfire-night.jpg',
    featured: false,
    highlights: ['Road villages', 'Paragliding valley', 'Monastery mornings'],
    status: 'published',
  },
]
